ISO3166 = {
	'AD': 'Andorra',
	'AE': 'Emiratos Árabes Unidos',
	'AF': 'Afganistán',
	'AG': 'Antigua & Barbuda',
	'AI': 'Anguilla',
	'AL': 'Albania',
	'AM': 'Armenia',
	'AN': 'Antillas Neerlandesas',
	'AO': 'Angola',
	'AQ': 'Antártida',
	'AR': 'Argentina',
	'AS': 'Samoa Estadounidense',
	'AT': 'Austria',
	'AU': 'Australia',
	'AW': 'Aruba',
	'AZ': 'Azerbaiyán',
	'BA': 'Bosnia y Herzegovina',
	'BB': 'Barbados',
	'BD': 'Bangladesh',
	'BE': 'Bélgica',
	'BF': 'Burkina Faso',
	'BG': 'Bulgaria',
	'BH': 'Bahrain',
	'BI': 'Burundi',
	'BJ': 'Benín',
	'BM': 'Bermudas',
	'BN': 'Brunei Darussalam',
	'BO': 'Bolivia',
	'BR': 'Brasil',
	'BS': 'Bahamas',
	'BT': 'Bután',
	'BU': 'Birmania (NE)',
	'BV': 'Isla Bouvet',
	'BW': 'Botsuana',
	'BY': 'Bielorrusia',
	'BZ': 'Belice',
	'CA': 'Canadá',
	'CC': 'Islas Cocos (Keeling)',
	'CF': 'República Centroafricana',
	'CG': 'Congo',
	'CH': 'Suiza',
	'CI': 'Costa de Marfil',
	'CK': 'Islas Cook',
	'CL': 'Chile',
	'CM': 'Camerún',
	'CN': 'China',
	'CO': 'Colombia',
	'CR': 'Costa Rica',
	'CS': 'Checoslovaquia (NE)',
	'CU': 'Cuba',
	'CV': 'Cabo Verde',
	'CX': 'Isla de Navidad',
	'CY': 'Chipre',
	'CZ': 'República Checa',
	'DD': 'República Democrática Alemana (NE)',
	'DE': 'Alemania',
	'DJ': 'Yibuti',
	'DK': 'Dinamarca',
	'DM': 'Dominica',
	'DO': 'República Dominicana',
	'DZ': 'Algeria',
	'EC': 'Ecuador',
	'EE': 'Estonia',
	'EG': 'Egipto',
	'EH': 'Sahara Occidental',
	'ER': 'Eritrea',
	'ES': 'España',
	'ET': 'Etiopía',
	'FI': 'Finlandia',
	'FJ': 'Fiyi',
	'FK': 'Islas Malvinas',
	'FM': 'Micronesia',
	'FO': 'Islas Feroe',
	'FR': 'Francia',
	'FX': 'Francia Metropolitana',
	'GA': 'Gabón',
	'GB': 'Reino Unido',
	'GD': 'Granada',
	'GE': 'Georgia',
	'GF': 'Guayana Francesa',
	'GH': 'Ghana',
	'GI': 'Gibraltar',
	'GL': 'Groenlandia',
	'GM': 'Gambia',
	'GN': 'Guinea',
	'GP': 'Guadalupe',
	'GQ': 'Guinea Ecuatorial',
	'GR': 'Grecia',
	'GS': 'Islas Georgias del Sur y Sándwich del Sur',
	'GT': 'Guatemala',
	'GU': 'Guam',
	'GW': 'Guinea-Bissau',
	'GY': 'Guyana',
	'HK': 'Hong Kong',
	'HM': 'Islas Heard y McDonald',
	'HN': 'Honduras',
	'HR': 'Croacia',
	'HT': 'Haití',
	'HU': 'Hungría',
	'ID': 'Indonesia',
	'IE': 'Irlanda',
	'IL': 'Israel',
	'IN': 'India',
	'IO': 'Territorio Británico del Océano Índico',
	'IQ': 'Irák',
	'IR': 'República Islámica de Irán',
	'IS': 'Islandia',
	'IT': 'Italia',
	'JM': 'Jamaica',
	'JO': 'Jordania',
	'JP': 'Japón',
	'KE': 'Kenia',
	'KG': 'Kirguistán',
	'KH': 'Camboya',
	'KI': 'Kiribati',
	'KM': 'Comoras',
	'KN': 'San Cristóbal y Nieves',
	'KP': 'República Popular Democrática de Corea',
	'KR': 'República de Corea',
	'KW': 'Kuwait',
	'KY': 'Islas Caimán',
	'KZ': 'Kazajstán',
	'LA': 'República Democrática Popular de Laos',
	'LB': 'Líbano',
	'LC': 'Santa Lucía',
	'LI': 'Liechtenstein',
	'LK': 'Sri Lanka',
	'LR': 'Liberia',
	'LS': 'Lesotho',
	'LT': 'Lituania',
	'LU': 'Luxemburgo',
	'LV': 'Letonia',
	'LY': 'Jamahiriya Árabe Libia',
	'MA': 'Marruecos',
	'MC': 'Mónaco',
	'MD': 'República de Moldavia',
	'MG': 'Madagascar',
	'MH': 'Islas Marshall',
	'ML': 'Malí',
	'MN': 'Mongolia',
	'MM': 'Myanmar',
	'MO': 'Macao',
	'MP': 'Islas Marianas del Norte',
	'MQ': 'Martinica',
	'MR': 'Mauritania',
	'MS': 'Monserrat',
	'MT': 'Malta',
	'MU': 'Mauricio',
	'MV': 'Maldivas',
	'MW': 'Malawi',
	'MX': 'México',
	'MY': 'Malasia',
	'MZ': 'Mozambique',
	'NA': 'Namibia',
	'NC': 'Nueva Caledonia',
	'NE': 'Níger',
	'NF': 'Isla de Norfolk',
	'NG': 'Nigeria',
	'NI': 'Nicaragua',
	'NL': 'Países Bajos',
	'NO': 'Noruega',
	'NP': 'Nepal',
	'NR': 'Nauru',
	'NT': 'Zona Neutral (NE)',
	'NU': 'Niue',
	'NZ': 'Nueva Zelanda',
	'OM': 'Omán',
	'PA': 'Panamá',
	'PE': 'Perú',
	'PF': 'Polinesia Francesa',
	'PG': 'Papúa Nueva Guinea',
	'PH': 'Filipinas',
	'PK': 'Pakistán',
	'PL': 'Polonia',
	'PM': 'San Pedro y Miquelón',
	'PN': 'Pitcairn',
	'PR': 'Puerto Rico',
	'PT': 'Portugal',
	'PW': 'Palaos',
	'PY': 'Paraguay',
	'QA': 'Qatar',
	'RE': 'Reunión',
	'RO': 'Rumanía',
	'RU': 'Federación Rusa',
	'RW': 'Ruanda',
	'SA': 'Arabia Saudita',
	'SB': 'Islas Salomón',
	'SC': 'Seychelles',
	'SD': 'Sudán',
	'SE': 'Suecia',
	'SG': 'Singapur',
	'SH': 'Santa Elena',
	'SI': 'Eslovenia',
	'SJ': 'Islas Svalbard y Jan Mayen',
	'SK': 'Eslovaquia',
	'SL': 'Sierra Leona',
	'SM': 'San Marino',
	'SN': 'Senegal',
	'SO': 'Somalia',
	'SR': 'Surinam',
	'ST': 'Santo Tomé y Príncipe',
	'SU': 'Unión de Repúblicas Socialistas Soviéticas (NE)',
	'SV': 'El Salvador',
	'SY': 'República Árabe Siria',
	'SZ': 'Suazilandia',
	'TC': 'Islas Turcas y Caicos',
	'TD': 'Chad',
	'TF': 'Territorios Australes Franceses',
	'TG': 'Togo',
	'TH': 'Tailandia',
	'TJ': 'Tayikistán',
	'TK': 'Tokelau',
	'TM': 'Turkmenistán',
	'TN': 'Túnez',
	'TO': 'Tonga',
	'TP': 'Timor Oriental',
	'TR': 'Turquía',
	'TT': 'Trinidad y Tobago',
	'TV': 'Tuvalu',
	'TW': 'Taiwán',
	'TZ': 'República Unida de Tanzania',
	'UA': 'Ucrania',
	'UG': 'Uganda',
	'UM': 'Islas periféricas menores de los Estados Unidos',
	'US': 'Estados Unidos de América',
	'UY': 'Uruguay',
	'UZ': 'Uzbekistán',
	'VA': 'Estado de la Ciudad del Vaticano (Santa Sede)',
	'VC': 'San Vicente y las Granadinas',
	'VE': 'Venezuela',
	'VG': 'Islas Vírgenes Británicas',
	'VI': 'Islas Vírgenes de los Estados Unidos',
	'VN': 'Vietnam',
	'VU': 'Vanuatu',
	'WF': 'Islas Wallis y Futuna',
	'WS': 'Samoa',
	'YD': 'Yemen democrático (NE)',
	'YE': 'Yemen',
	'YT': 'Mayotte',
	'YU': 'Yugoslavia (NE)',
	'ZA': 'Sudáfrica',
	'ZM': 'Zambia',
	'ZR': 'Zaire',
	'ZW': 'Zimbabwe',
	'ZZ': 'País desconocido o no especificado',
}

def countryname(arg):
	if arg in ISO3166:
		return ISO3166[str(arg)]
	else:
		return arg